-- +goose Up
CREATE TABLE users(
    ID UUID PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(255) UNIQUE
);
-- +goose Down
DROP TABLE users;
